# Generated by Django 5.0.1 on 2024-02-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_company_options_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id']},
        ),
    ]
